language: php
php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

script:
    - composer validate
    - make test

before_script:
    - travis_retry composer install --no-interaction --prefer-dist

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
