name: Testy

on:
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.1', '7.2', '7.3', '7.4']
    name: Jednotkové testy
    steps:
      - name: Informace o prostředí
        run: |
          env

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer
          coverage: none

      - name: Composer
        run: |
          composer validate
          composer install

      - name: Jednotkové testy
        run: |
          make test
